apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 3
  template:
    metadata:
      name: blue-pod
      labels:
        color: blue
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      color: blue
