apiVersion: v1
kind: Pod
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  containers:
  - envFrom:
    - configMapRef:
        name: app-config
    image: simple-website
    name: simple-website
