apiVersion: v1
kind: Pod
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  containers:
    - name: simple-website
      image: simple-website
      ports:
        - containerPort: 8080
      env:
        - name: PROFILE
          valueFrom:
            configMapKeyRef:
              key: prod

      envFrom:
        - configMapRef:
            name: app_mode
