apiVersion: v1
kind: Pod
metadata:
  labels:
    app: custom-schduler
spec:
  containers:
    - name: kube-schduler
      image: k8s.gcr.io/kube-scheduler-amd64:v1.11.3
      imagePullPolicy: IfNotPresent
    - command:
        - kube-schduler
        - --address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true
      name: kube-scheduler
  restartPolicy: Always
