apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-pod
spec:
  containers:
    - name: web-pod
      image: ubuntu
      command:
        - "sleep"
        - "3600"
      securityContext:
        runAsUser: 1000
        capabilities:
          add:
            - "MAC_ADMIN"
