apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    app:
spec:
  containers:
    - name: alpine
      image: alpine
      volumeMounts:
        - mountPath: /opt
          name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: Directory
