apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
  labels:
    app: multi-container-app
spec:
  containers:
    - name: multi-container-app
      image: simple-webapp
      command:
        - sleep
        - "1000"
    - name: log-agent
      image: log-agent
