apiVersion: v1
kind: Pod
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  containers:
    - name: simple-website
      image: simple-website
      ports:
        - containerPort: 8080
  volumes:
    - name: app-secret
      secret:
        secretName: app-secret
