apiVersion: v1
kind: Pod
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  containers:
    - name: simple-website
      image: simple-website
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
